import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>twitch website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <Sidebar/>
    </div>
    </div>
  )
}
